package com.myklovr.helpers.constants;

public class AppConstants {

	public static final String MYKLOVR_PROVIDER = "myklovr";
	public static final String FACEBOOK_PROVIDER = "facebook";
	public static final String TWITTER_PROVIDER = "twitter";
	public static final String GPLUS_PROVIDER = "google";
	
	public static final String USER_PROFILE_SECTION_KIND = "SECTION_KIND";
	public static final String USER_PROFILE_SECTION_BASIC_INFO = "SECTION_BASIC_INFO";
	public static final String USER_PROFILE_SECTION_PURPOSE_ACCADEMIC_GROWTH = "USER_PROFILE_SECTION_PURPOSE_ACCADEMIC_GROWTH";
	public static final String USER_PROFILE_SECTION_PURPOSE_PERSONAL_GROWTH = "USER_PROFILE_SECTION_PURPOSE_PERSONAL_GROWTH";
	public static final String USER_PROFILE_SECTION_PURPOSE_PROFESSIONAL_GROWTH = "USER_PROFILE_SECTION_PURPOSE_PROFESSIONAL_GROWTH";
	public static final String USER_PROFILE_SECTION_PURPOSE_RECRUIOTONG_GROWTH = "USER_PROFILE_SECTION_PURPOSE_RECRUIOTONG_GROWTH";
	public static final String USER_PROFILE_SECTION_PURPOSE_MARKET = "USER_PROFILE_SECTION_PURPOSE_MARKET";
	public static final String USER_PROFILE_SECTION_PURPOSE_PROMOTING = "USER_PROFILE_SECTION_PURPOSE_PROMOTING";
	public static final String USER_PROFILE_SECTION_PURPOSE_RESEARCH_DEVELOPMENT = "USER_PROFILE_SECTION_PURPOSE_RESEARCH_DEVELOPMENT";
	public static final String USER_PROFILE_SECTION_PURPOSE_CAREER_SERVICES = "USER_PROFILE_SECTION_PURPOSE_CAREER_SERVICES";
	
	
	public static final int ERROR_INTERNAL = -1;
	public static final int OK_CODE = 0;
	public static final int WARNING_CODE = 1;
	
	
}
